### ISSUE TITLE
Ссылка вне tips

### ISSUE THREAD

**Issue by anastasiatranslator** [danila-shirkov/exercises-css#1]
https://github.com/danila-shirkov/exercises-css/blob/d0b3ac5530f47eb8224a557deb271d380e9295cc/modules/10-basics/10-introduction/description.es.yml#L8

**Comment by danila-shirkov** [comment]
Это надо будет изменить на относительный путь. Но как это убдет работать можно проверит только на проде. Пока оставляем так, посмотрим что будет на сайте
