### ISSUE TITLE
Несоответствие

### ISSUE THREAD

**Issue by anastasiatranslator** [danila-shirkov/exercises-css#2]
https://github.com/danila-shirkov/exercises-css/blob/78e31fb057c2ac07de93ff47ccf2bcdaeceb2c38/modules/30-box/10-border-style/description.es.yml#L34C9-L34C9

@yana-fesenko @danila-shirkov в испанском тексте, 34-41 строки, есть пояснения английских терминов, чего нет в ИТ на русском, что делать в таком случае? спасибо!

**Comment by danila-shirkov** [comment]
Здесь будем смотреть по смыслу, он не меняется, но дается больше разъяснений. Оставляем.
