### ISSUE TITLE
Меньше строк

### ISSUE THREAD

**Issue by anastasiatranslator** [danila-shirkov/exercises-css#3]
https://github.com/danila-shirkov/exercises-css/blob/125b19fdfafa70b1c1dff8db0f8af2d79150d34f/modules/40-flex/30-flex-alignment/description.es.yml#L71

Пропущена одна строка из ИТ на русском

**Comment by danila-shirkov** [comment]
Смысл не потерялся, просто предложения идут одним параграфом в переводе. Разделить на два как в оригинале

**Comment by yana-fesenko** [comment]
@anastasiatranslator посмотри, пожалуйста
